name: desktop Lighthouse
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.6.x
          lhci autorun --collect.url=https://www.heydoc.pl/s/article/E-recepta-co-warto-o-niej-wiedziec-Jak-otrzymac-recepte-online 
          ls -R
          node parsing_desktop.js
          lhci autorun --collect.url=https://www.heydoc.pl/s/
          ls -R
          node parsing_desktop.js      


      - name: Commit files # commit the output folder 
        run: |
          git config --local user.email "test@github.com"
          git config --local user.name "GitHub Action test"
          git add ./output
          git commit -m "Add desktop"
          git pull
          git push --force
