name: Mobile Lighthouse
on: pull_request
jobs:
  lhci:
    name: Lighthouse Mobile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.6.x
          
          #PROD
          lhci autorun --collect.url=https://www.heydoc.pl/s/article/E-recepta-co-warto-o-niej-wiedziec-Jak-otrzymac-recepte-online --config=./lighthouserc_mobile.json
          ls -R
          node parsing_mobile.js      
          
          lhci autorun --collect.url=https://www.heydoc.pl/s/ --config=./lighthouserc_mobile.json
          ls -R
          node parsing_mobile.js      
          
          #UAT
          lhci autorun --collect.url=https://uatpartial-healthcloudtrialmaster-15a4d-16dc9b5b004.cs108.force.com/pp/s/article/Co-to-jest-synapsa --config=./lighthouserc_mobile.json
          ls -R
          node parsing_mobile.js      
          
          lhci autorun --collect.url=https://uatpartial-healthcloudtrialmaster-15a4d-16dc9b5b004.cs108.force.com/pp/s/ --config=./lighthouserc_mobile.json
          ls -R
          node parsing_mobile.js      
          
          #TEST
          lhci autorun --collect.url=https://pptest-healthcloudtrialmaster-15a4d-16dc9b5b004.cs101.force.com/pp/s/article/test-s --config=./lighthouserc_mobile.json
          ls -R
          node parsing_mobile.js      
          
          lhci autorun --collect.url=https://pptest-healthcloudtrialmaster-15a4d-16dc9b5b004.cs101.force.com/pp/s/ --config=./lighthouserc_mobile.json
          ls -R
          node parsing_mobile.js      
          

      - name: Commit files # commit the output folder 
        run: |
          git config --local user.email "test@github.com"
          git config --local user.name "GitHub Action test"
          git add ./output
          git commit -m "Add mobile"
          git pull
          git push --force
