name: Mobile Lighthouse
on: [push]
jobs:
  lhci:
    name: Lighthouse Mobile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.6.x
          lhci autorun --collect.url=https://www.heydoc.pl/s/article/E-recepta-co-warto-o-niej-wiedziec-Jak-otrzymac-recepte-online --config=./lighthouserc_mobile.json
          node parsing_mobile.js
          
          lhci autorun --collect.url=https://www.heydoc.pl/s/ --config=./lighthouserc_mobile.json
          node parsing_mobile.js      
          
          ls -R

      - name: Commit files # commit the output folder 
        run: |
          git config --local user.email "test@github.com"
          git config --local user.name "GitHub Action test"
          git add ./output
          git commit -m "Add mobile"
          git pull
          git push --force
